"""genbodies.py -- write MODELDEF, VRAVATAR, CVARINFO and the actor classes from what is
installed.

    python genbodies.py

Reads models/avatars/*/ and generates, for every body that has a model and a measured
.avatar beside it:

    MODELDEF.txt              one block per body
    VRAVATAR.txt              one entry per body
    CVARINFO.txt              the settings, plus fit-mode storage per body per hand
    zscript/avatar/bodies.zs  one actor class per body

GENERATED, NOT HAND-WRITTEN, for two specific reasons:

  - A MODELDEF block naming a class that does not exist is a FATAL error at startup, about
    eight seconds in, with nothing useful logged -- the kind of fault found by bisecting a
    file. Generating the classes and the blocks from one list means they cannot disagree.
  - Fit mode saves six numbers per hand per body into an archived cvar, and a cvar can only
    be created by CVARINFO, never from script. A body missing its pair cannot be fitted at
    all, and fit mode would have nowhere to write.

Run install_avatars.py first; it puts the models in and measures them.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
AVATARS = os.path.join(HERE, "models", "avatars")


def pretty(name):
    """A body's name as a person would read it."""
    words = name.replace("_", " ").split()
    out = []
    for w in words:
        if w.lower() in ("c", "rs"):
            out.append(w.upper())
        else:
            out.append(w[:1].upper() + w[1:])
    return " ".join(out)

def camel(name):
    return "".join(p.capitalize() for p in name.split("_"))


def find_bodies():
    out = []
    if not os.path.isdir(AVATARS):
        return out
    for name in sorted(os.listdir(AVATARS)):
        d = os.path.join(AVATARS, name)
        if not os.path.isdir(d):
            continue
        mdl = [f for f in sorted(os.listdir(d)) if f.lower().endswith(".mdl")]
        avf = [f for f in sorted(os.listdir(d)) if f.lower().endswith(".avatar")]
        if not mdl:
            print("  skipped %-22s no .mdl in its folder" % name)
            continue
        if not avf:
            print("  skipped %-22s no .avatar -- run install_avatars.py" % name)
            continue
        tier = "?"
        has_handrest = False
        try:
            for line in open(os.path.join(d, avf[0]), encoding="utf-8"):
                t = line.strip()
                if line.startswith("tier"):
                    tier = line.split()[1]
                if t.startswith("handrest"):
                    has_handrest = True
        except OSError:
            pass

        # THE ENGINE'S CONTRACT, APPLIED HERE TOO. Without `handrest` the engine cannot build
        # O_hand, so the hand takes the controller's raw rotation and faces wherever the grip
        # faces -- and the avatar registry refuses the body outright. Writing it into the menu
        # anyway offers the player a body that cannot load.
        #
        # Checked as a rule, not by name: fix a body's measurements and it comes back with no
        # code change. doomslayer_lowpoly is the one this drops today.
        if not has_handrest:
            print("  skipped %-22s no `handrest` in its .avatar -- the engine refuses it" % name)
            continue
        out.append(dict(name=name, cls="RSA_" + camel(name), mdl=mdl[0],
                        avatar=avf[0], tier=tier))
    return out


MODELDEF_HEAD = """\
// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.
//
// One block per avatar actor. A MODELDEF block binds to exactly the class it names and not
// to its children, and a block naming a class that does not exist is FATAL at startup with
// nothing useful logged -- so these are generated from the same list as the classes and can
// never disagree with them.
//
// The models are Valve Source .mdl and are loaded as such. Nothing is converted: the file
// measured by tools/avatar/measure_avatar.py is the file drawn here.
//
// Scale is 1 on purpose. The body is sized every frame by the player's own eye height
// against the model's measured eye height -- a typed scale would be a tuned constant about
// a model, which is the thing this rebuild exists to remove.

"""

VRAVATAR_HEAD = """\
// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.
//
// Which bodies exist (VR_BODY_HANDS_SPEC.md C.4). `vr_avatar "<name>"` picks one; empty
// means none, and with none nothing is spawned, drawn or hooked.
//
// Another mod adds a body by shipping its own VRAVATAR lump beside its model, with no edit
// to this file and no engine change. The list is the union of them all.

"""

BODIES_HEAD = """\
// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.
//
// One class per body, because a MODELDEF block binds to the class it names and NOT to its
// children -- a single shared class with the model chosen at runtime is not possible without
// an engine change. Everything that makes an avatar an avatar lives in RSA_AvatarBase
// (actor.zs); these exist only to be named.

"""

CVARINFO_HEAD = """\
// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.
//
// `user` and archived, so a choice follows the player and survives a restart.

"""

CVARINFO_BASE = """\
// Which body to wear. A name from a VRAVATAR lump; empty means none, and with none nothing
// is spawned, drawn or hooked -- the mod is inert.
user string vr_avatar = "%s";

// Draw the WHOLE body from your own eyes, rather than only the hands and forearms.
//
// Off by default: until the arm solve lands (M3) the arms follow the hands rigidly, and a
// torso attached to them is visibly wrong seen from the inside. This exists so a body can
// be looked at on purpose anyway.
//
// It does not affect a mirror, a spectator or another player -- they always see the whole
// body, because what is hidden is decided per view, not in the pose.
user bool vr_avatar_fullbody = false;

// Draw the avatar's joints as axes (level 2 of the rig debug drawing).
user bool vr_avatar_debug = false;

// The in-game mirror. It hangs itself in front of you when you switch it on and stays put,
// so you can walk up to it and turn side-on -- which is most of what a mirror is for.
//
// A MONITOR, NOT A REFLECTION, and deliberately: the camera stands at the panel and TRACKS
// you, so you stay in frame while you walk, crouch and lean. A true reflection loses you the
// moment you step aside, which is exactly when you were trying to look at yourself.
//
// It renders the whole scene a second time. Switch it on to check something, off after.
user bool vr_mirror = false;
user float vr_mirror_dist = 96.0;       // how far in front of you it stands
user float vr_mirror_up = 34.0;         // its centre above your feet
user float vr_mirror_fov = 70.0;        // how much of you it takes in
user float vr_mirror_standoff = 8.0;    // camera clear of its own panel; see mirror.zs

// ---- the body fit (VR_BODY_HANDS_SPEC.md M3 task 3) ------------------------
//
// Measured off the player by `vr_fitmode body`: stand straight, both arms out to the sides,
// hold the trigger. Everything downstream scales from these two -- the avatar's world scale,
// and how far the arm solver reaches.
//
// Zero means never fitted. The engine then assumes the player is built like the body he is
// wearing, which is visibly wrong for a tall player on a short model and honest about it
// rather than quietly guessing.
user float vr_fit_height = 0.0;      // eye height standing, metres
user float vr_fit_armspan = 0.0;     // wrist to wrist, arms out, metres

// ---- fit mode storage (VR_BODY_HANDS_SPEC.md C.5) --------------------------
//
// Six numbers as one string: "x y z pitch yaw roll". Offsets are in the hand frame;
// rotations apply pitch about X, yaw about Z, roll about Y, in that order.
//
// ONE STRING AND NOT SIX CVARS: forty-two cvars for seven bodies is a config file nobody
// can read, and the six are only ever set or cleared together.
//
// Empty means never fitted, which is not an error -- the engine then uses the fit derived
// from the model's own measurements (spec B.5).

"""


def main():
    bodies = find_bodies()
    if not bodies:
        sys.stderr.write("genbodies: no bodies installed -- run install_avatars.py first\n")
        return 1

    with open(os.path.join(HERE, "MODELDEF.txt"), "w", encoding="utf-8", newline="") as w:
        w.write(MODELDEF_HEAD)
        for b in bodies:
            w.write("Model %s\n{\n" % b["cls"])
            w.write("\tPath \"models/avatars/%s\"\n" % b["name"])
            w.write("\tModel 0 \"%s\"\n" % b["mdl"])
            w.write("\tScale 1.0 1.0 1.0\n")
            w.write("\tUSEACTORPITCH\n\tUSEACTORROLL\n")
            w.write("\tFrameIndex PIST A 0 0\n}\n\n")

    with open(os.path.join(HERE, "VRAVATAR.txt"), "w", encoding="utf-8", newline="") as w:
        w.write(VRAVATAR_HEAD)
        for b in bodies:
            w.write("avatar %s\n{\n" % b["name"])
            w.write("\tactor  \"%s\"\n" % b["cls"])
            w.write("\tdata   \"models/avatars/%s/%s\"\n}\n\n" % (b["name"], b["avatar"]))

    with open(os.path.join(HERE, "zscript", "avatar", "bodies.zs"),
              "w", encoding="utf-8", newline="") as w:
        w.write(BODIES_HEAD)
        for b in bodies:
            w.write("// %s, %s\n" % (b["name"],
                                     "fingers" if b["tier"] == "Full" else b["tier"]))
            w.write("class %s : RSA_AvatarBase {}\n\n" % b["cls"])

    with open(os.path.join(HERE, "CVARINFO.txt"), "w", encoding="utf-8", newline="") as w:
        w.write(CVARINFO_HEAD)
        w.write(CVARINFO_BASE % bodies[0]["name"])
        for b in bodies:
            for side in ("R", "L"):
                w.write("user string vr_fit_hand_%s_%s = \"\";\n" % (b["name"], side))
            w.write("\n")


    # ---- MENUDEF ---------------------------------------------------------
    #
    # THE ONLY INTERFACE THERE IS. The person using this is wearing a headset: he cannot
    # reach a keyboard, read a console or type a cvar name, so anything that is only a
    # console command does not exist as far as he is concerned.
    #
    # Generated with everything else, so the body list can never offer something that is not
    # installed -- picking a missing body would spawn nothing and say so in a console he
    # cannot see.
    with open(os.path.join(HERE, "MENUDEF.txt"), "w", encoding="utf-8", newline="") as w:
        w.write("// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.\n\n")

        w.write("OptionString \"RSA_BodyList\"\n{\n")
        # "none", NOT the empty string. The option menu decides whether a list is numbers
        # or strings by testing whether the FIRST entry's value is empty -- an empty first
        # value sends the whole list down the numeric path, where it matches nothing and
        # the control shows its first entry forever whatever you pick. That is exactly what
        # it did: the body could not be changed from Off.
        w.write("\t\"none\", \"Off (no body)\"\n")
        for b in bodies:
            w.write("\t\"%s\", \"%s\"\n" % (b["name"], pretty(b["name"])))
        w.write("}\n\n")

        w.write("""OptionMenu "RSA_AvatarOptions"
{
\tTitle "VR BODY AND HANDS"

\tStaticText ""
\tOption "Body", "vr_avatar", "RSA_BodyList"
\tOption "Mirror", "vr_mirror", "OnOff"
\tStaticText ""

\tStaticText "Fitting", gold
\tStaticText "Do the body first: it sizes everything else.", darkgray
\tCommand "Fit my body (stand in a T)", "vr_fitmode_body"
\tCommand "Fit my hands", "vr_fitmode_hand"
\tCommand "Fit the weapon I am holding", "vr_fitmode_weapon"
\tCommand "Done fitting", "vr_fitmode_off"
\tStaticText ""

\tStaticText "Looking at it", gold
\tOption "Show the whole body from inside", "vr_avatar_fullbody", "OnOff"
\tOption "Draw the hand axes", "vr_rig_debug", "OnOff"
\tOption "Draw the avatar's joints", "vr_avatar_debug", "OnOff"
\tStaticText ""

\tStaticText "Your measurements", gold
\tStaticText "Set by the body fit. Zero means never fitted.", darkgray
\tOption "Use the virtual controller (desk testing)", "vr_rig_fake", "OnOff"
}

""")

        # Hang it off the main options menu, so it is where he would look for it.
        w.write("""AddOptionMenu "OptionsMenu"
{
\tSubmenu "VR Body and Hands", "RSA_AvatarOptions"
}
""")

    print("genbodies: wrote MODELDEF.txt, VRAVATAR.txt, CVARINFO.txt, MENUDEF.txt "
          "and zscript/avatar/bodies.zs")
    for b in bodies:
        print("  %-22s %-26s %-36s %s" % (b["name"], b["cls"], b["mdl"], b["tier"]))
    print("\nPick one in game with:  vr_avatar %s" % bodies[0]["name"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
