// RS_Avatar -- the avatar actor.
//
// VR_BODY_HANDS_SPEC.md M1 task 1.
//
// WHAT THIS ACTOR IS FOR. It is a place for the engine to hang a model and a bone palette
// on. It has no gameplay: it does not block, does not take damage, does not collide, and
// nothing in the playsim asks it anything. The rig poses it every displayed frame; the
// actor's own job is only to exist somewhere sensible so the renderer culls and lights it
// like any other model.
//
// WHY IT IS A WORLD ACTOR AND NOT A PSPRITE. A psprite is drawn after the world with its
// own projection, so it takes no world lighting, casts nothing, and cannot be seen by
// anything -- including a mirror, and including another player. A body has to be in the
// world to be a body.

class RSA_AvatarBase : Actor
{
	Default
	{
		// BIG RADIUS ON PURPOSE. The rig moves the drawn model away from the actor's own
		// position -- under the headset, which can be most of a metre from where the actor
		// stands. Culling is done against the actor, so a tight radius culls a body that
		// is plainly on screen, and it does it only at certain angles, which reads as
		// flickering rather than as a culling bug.
		Radius 64;
		Height 8;

		+NOINTERACTION      // no gravity, no movement, no thinking beyond its own Tick
		+NOBLOCKMAP         // never in the way of a shot or a step
		+NOGRAVITY
		+NOTELEPORT
		+DONTSPLASH
		+SYNCHRONIZED       // no playsim randomness of its own
		+NODAMAGE
		+NOBLOOD

		// THIN AIR, NOT INVISIBLE. +INVISIBLE would also stop the model drawing.
		RenderStyle "Normal";
		Alpha 1.0;
	}

	States
	{
	Spawn:
		// A REAL SPRITE, AND THIS IS THE WHOLE REASON NO BODY EVER APPEARED.
		//
		// TNT1 is the engine's "no sprite" name. An actor on a TNT1 frame is skipped by the
		// renderer BEFORE it looks for a model, so the body spawned, was posed every frame,
		// logged nothing, and drew nothing -- for days. RS_WorldHands' own drawn hand
		// carries the same warning beside the same line, and this file did not heed it.
		//
		// PIST is an IWAD sprite, so it exists with nothing but Doom loaded. It is never
		// seen: MODELDEF binds the model to this frame and the model replaces the sprite.
		PIST A -1;
		Stop;
	}

	// VRRigRole is render-only state the engine reads while drawing, and it is not
	// serialized -- so it has to be re-asserted, not set once. Set here rather than from
	// the handler so an avatar spawned by anything at all is still a complete avatar.
	// Set once, so the surface hide below is only asked for once.
	private bool mHasModelData;

	override void Tick()
	{
		Super.Tick();
		VRRigRole = 1;      // 1 = avatar body (spec B.3 item 5)

		// MODEL DATA, SO A SURFACE CAN BE HIDDEN.
		//
		// The universal helmet needs the body's OWN helmet surfaces switched off, or he
		// wears two. SetModelSurfaceHidden writes to modelData, and MODELDEF alone never
		// creates that -- only A_ChangeModel does. Without it the hide returns false and
		// fails silently, which is exactly what the log reported the first time.
		//
		// Binding this actor's OWN class is the whole call: MODELDEF is keyed on the class,
		// so the model drawn is the one already being drawn and nothing about the body
		// changes. ChangeModel destroys the data again if it would be empty
		// (p_actionfunctions.cpp), and naming a modeldef is what keeps it alive.
		//
		// Once. It is not free, and re-asserting it every tic would be 35 allocations a
		// second for a thing that does not change.
		if (!mHasModelData)
		{
			mHasModelData = true;
			A_ChangeModel(GetClassName());
		}
	}
}

// The per-body classes are in bodies.zs, generated by genbodies.py from what is actually
// installed -- a MODELDEF block naming a class that does not exist is fatal at startup with
// nothing logged, so the classes and the blocks are written from one list.
