// GENERATED BY genbodies.py -- DO NOT EDIT BY HAND.
//
// One class per body, because a MODELDEF block binds to the class it names and NOT to its
// children -- a single shared class with the model chosen at runtime is not possible without
// an engine change. Everything that makes an avatar an avatar lives in RSA_AvatarBase
// (actor.zs); these exist only to be named.

// c_doom_marine, fingers
class RSA_CDoomMarine : RSA_AvatarBase {}

// dark_ages_praetor, fingers
class RSA_DarkAgesPraetor : RSA_AvatarBase {}

// doomslayer_default, fingers
class RSA_DoomslayerDefault : RSA_AvatarBase {}

// lillwasa_doomguy, fingers
class RSA_LillwasaDoomguy : RSA_AvatarBase {}

// marine_guy_classic, fingers
class RSA_MarineGuyClassic : RSA_AvatarBase {}

// pechenko_doomslayer, fingers
class RSA_PechenkoDoomslayer : RSA_AvatarBase {}

